In [1]:
def merge_sort(arr,beg,end,brr):
    if(beg<end):
        mid=int((beg+end)/2)
        merge_sort(arr,beg,mid,brr)
        merge_sort(arr,mid+1,end,brr)
        merge(arr,beg,end,brr)
        

In [2]:
def merge(arr,beg,end,brr):
    mid=int((beg+end)/2)
    i=beg
    j=mid+1
    k=0
    while(i<(mid+1) and j<end):
        if(arr[i]<arr[j]):
            brr[k]=arr[i]
            print(brr[k])
            i=i+1
            k=k+1
        else:
            brr[k]=arr[j]
            print(brr[k])
            j=j+1
            k=k+1
    while(i<(mid+1) and j>=end):
        brr[k]=arr[i]
        print(brr[k])
        i=i+1
        k=k+1
    while(j<end and i>=(mid+1)):
        brr[k]=arr[j]
        print(brr[k])
        j=j+1
        k=k+1
    
 

In [3]:

import numpy as np
list=[1,7,8,4,2,5]
arr=np.array(list)
print(arr)
brr=np.ndarray(shape=(6),dtype=int)
merge_sort(arr,0,6,brr)
#merge(arr,0,5,brr)
print(brr)


[1 7 8 4 2 5]
1
8
1
7
8
2
2
5
1
2
5
7
8
4
[1 2 5 7 8 4]


In [4]:
if __name__ == '__main__': 
    import numpy as np
    brr=np.ndarray(shape=(5),dtype=int)
    arr = [12, 11, 13, 5, 6]  
    print ("Given array is", end ="\n")  
    print(arr)
    merge_sort(arr,0,5,brr)
    print("Sorted array is: ", end ="\n") 
    print(brr)

Given array is
[12, 11, 13, 5, 6]
12
12
11
5
5
6
5
6
12
11
13
Sorted array is: 
[ 5  6 12 11 13]


In [5]:
def mergeSort(myList):
    if len(myList) > 1:
        mid = len(myList) // 2
        left = myList[:mid]
        right = myList[mid:]

        # Recursive call on each half
        mergeSort(left)
        mergeSort(right)

        # Two iterators for traversing the two halves
        i = 0
        j = 0
        
        # Iterator for the main list
        k = 0
        
        while i < len(left) and j < len(right):
            if left[i] < right[j]:
              # The value from the left half has been used
              myList[k] = left[i]
              # Move the iterator forward
              i += 1
            else:
                myList[k] = right[j]
                j += 1
            # Move to the next slot
            k += 1

        # For all the remaining values
        while i < len(left):
            myList[k] = left[i]
            i += 1
            k += 1

        while j < len(right):
            myList[k]=right[j]
            j += 1
            k += 1

myList = [54,26,93,17,77,31,44,55,20]
mergeSort(myList)
print(myList)


[17, 20, 26, 31, 44, 54, 55, 77, 93]


In [6]:
b=5//2

In [7]:
b

2